# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ebs-snapshoter}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kris Rasmussen"]
  s.date = %q{2010-05-10}
  s.default_executable = %q{snapshoter}
  s.description = %q{Provides EBS snapshot automation that can be configured and run on an EC2 instance.}
  s.email = %q{kristopher.rasmussen@gmail.com}
  s.executables = ["snapshoter"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/snapshoter",
     "lib/snapshoter.rb",
     "lib/snapshoter/config.rb",
     "lib/snapshoter/manager.rb",
     "lib/snapshoter/provider/ec2.rb",
     "lib/snapshoter/volume.rb",
     "test/test_snapshoter.rb"
  ]
  s.homepage = %q{http://github.com/krisr/ebs-snapshoter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Provides EBS snapshot automation that can be configured and run on an EC2 instance.}
  s.test_files = [
    "spec/snapshoter_spec.rb",
     "spec/spec_helper.rb",
     "test/test_snapshoter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_aws>, [">= 0"])
      s.add_runtime_dependency(%q<mysql>, [">= 0"])
    else
      s.add_dependency(%q<right_aws>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
    end
  else
    s.add_dependency(%q<right_aws>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
  end
end

